name: tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip" # caching pip dependencies
          cache-dependency-path: "**/requirements/*.txt"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -e ["dev"].
          pip3 install pytest
          pip3 install pytest-cov
      - name: Pytest
        uses: liskin/gh-problem-matcher-wrap@v2
        with:
          linters: pytest
          run: pytest tests -v --cov=./ --cov-report=xml
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          env_vars: OS,PYTHON
          files: ./coverage.xml
          name: Coverage Report with codecov overview
          verbose: true
